export const BOOK_STATUSES = ['TO_READ', 'READING', 'READ', 'PAUSED', 'ABANDONED'];
export const MOOD_TAGS = ['MOVED', 'CALM', 'JOYFUL', 'SAD', 'ANGRY', 'CONFUSED', 'RELIEVED', 'EMPTY', 'CHANGED'];
export const TRACE_TYPES = ['DOG_EAR', 'ANNOTATION', 'REREAD_MARK'];
export const ACTIVITY_ACTIONS = ['CREATED', 'UPDATED', 'DELETED', 'RESTORED', 'STATUS_CHANGED', 'COMPLETED', 'MOVED', 'ARCHIVED', 'UNARCHIVED'];
export const ACTIVITY_ENTITY_TYPES = ['BOOK', 'DOG_EAR', 'ANNOTATION', 'REREAD_MARK', 'COMPLETION_REFLECTION', 'SHELF_LOCATION', 'BOOK_COPY'];
export const LOCATION_STATUSES = ['ACTIVE', 'ARCHIVED'];
export const COPY_STATUSES = ['SHELVED', 'ARCHIVED'];
export const COPY_MOVE_ACTIONS = ['PLACED', 'MOVED', 'REMOVED', 'ARCHIVED', 'UNARCHIVED'];
